CREATE TABLE IF NOT EXISTS usersinfo (
    uid  SERIAL PRIMARY KEY,
    ufname VARCHAR(50),
    ulname VARCHAR(50)
    );

ALTER TABLE usersinfo
ADD COLUMN IF NOT EXISTS uid  SERIAL PRIMARY KEY;
ALTER TABLE usersinfo
ADD COLUMN IF NOT EXISTS ufname VARCHAR(50);
ALTER TABLE usersinfo
ADD COLUMN IF NOT EXISTS ulname VARCHAR(50);