version: '3.1'

services:

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: server
    ports:
      - "8090:8090"
    networks:
     - net
    depends_on:
      - db

    
  db:
    image: postgres:15.1
    restart: unless-stopped
    container_name: pgdb
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "qwert"
      POSTGRES_DB: "usersList"
    ports:
     - "5433:5432"
    networks:
     - net
    volumes: 
      - pgdata:/var/lib/postgresql/data/


  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - net
    depends_on:
      - db
    links:
      - db:database


networks:
  net:

volumes:
  pgdata:
  