version: '3.1'

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: server
    ports:
      - "8090:8090"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: unless-stopped
    container_name: pgdb
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "qwert"
      POSTGRES_DB: "usersInfoDB"
    ports:
      - "2023:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data/


      
  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    container_name: adminer
    ports:
      - 8080:8080

volumes:
  pgdata: